[package]
name = "rpi-fan"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.4"
config = "0.10"
serde = { version = "1.0", features = ["derive"] }
